# Intro to NumPy

NumPy is the fundamental package for scientific computing with Python. It's used for working with arrays and contains functions for working in the domain of linear algebra, fourier transform, and matrices. In Python we have list, which serve the purpose of arrays, so why do we bother learning NumPy in the first place? Well, NumPy arrays are much faster than traditional Python lists and provide many supporting functions that make working with arrays easier. Part of why they're significantly faster is because the parts that require fast computation are written in C or C++.

Let's begin by importing NumPy and learning how to create NumPy arrays. If for some reason you don't have numpy installed, you will first have to go to your terminal (or Anaconda Prompt if on Windows) and enter the following:

conda install numpy

Make sure you've already installed Anaconda

In [138]:
# Importing NumPy
import numpy as np

# Creating Arrays and Common Methods
The first way of creating a NumPy array is by converting your existing Python list.

In [139]:
# Eaxmple code from pdf
# Create python list and print output
python_list = [1, 2, 3, 4, 5]
print(python_list)
print(type(python_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [140]:
# My example code
# Create python list and print output
py_list = [2, 4, 6, 8, 10]
print(py_list)
print(type(py_list))

[2, 4, 6, 8, 10]
<class 'list'>


In [141]:
# Example code from pdf
# Create numpy array and print output
numpy_array = np.array(python_list)
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [142]:
# My example code
# Create numpy array and print output
npy_array = np.array(py_list)
print(npy_array)
print(type(npy_array))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [143]:
# Example code from pdf
# 2d array list
python_2d_array = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(python_2d_array)
print(type(python_2d_array))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
<class 'list'>


In [144]:
# My example code
# # 2d array list
py_2d_array = [[10, 20, 30, 40, 50], [60, 70, 80, 90, 100], [110, 120, 130, 140, 150]]
print(py_2d_array)
print(type(py_2d_array))

[[10, 20, 30, 40, 50], [60, 70, 80, 90, 100], [110, 120, 130, 140, 150]]
<class 'list'>


In [145]:
# Example code from pdf
# 2d numpy array
numpy_2d_array = np.array(python_2d_array)
print(numpy_2d_array)
print(type(numpy_2d_array))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [146]:
# My example code
#2d numpy array
npy_2d_array = np.array(py_2d_array)
print(npy_2d_array)
print(type(npy_2d_array))

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
<class 'numpy.ndarray'>


In [147]:
# Example code from pdf
# arrange(start, stop)
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [148]:
# My example code
# arrange(start, stop)
np.arange(3, 11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
# Example code from pdf
# with steps
np.arange(0, 15, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [150]:
# My example code
# with steps
np.arange(0, 15, 4)

array([ 0,  4,  8, 12])

In [151]:
# Example code from pdf
# put in matrix
np.arange(0, 15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [152]:
# My example code
# put in matrix
np.arange(0, 10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [153]:
# Example code from pdf
# fill array with zeros
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [154]:
# My example code
# with array with zeros
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [155]:
# Example code from pdf
# put in matrix
np.zeros(15).reshape(3, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [156]:
# My example code
# put in matrix
np.zeros(4).reshape(2, 2)

array([[0., 0.],
       [0., 0.]])

In [157]:
# Example code from pdf
# fill array with ones
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [158]:
# My example code
# fill array with ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [159]:
#Example code from pdf
# put in matrix
np.ones(15).reshape(3, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [160]:
# My example code
# put in matrix
np.ones(9).reshape(3, 3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [161]:
# Example code from pdf
# change type float to integers
np.ones(15, dtype=int).reshape(3, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [162]:
# My example code
# change type float to integers
np.ones(9, dtype=int).reshape(3, 3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [163]:
# Example code from pdf
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [164]:
# My example code
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [165]:
# Example code from pdf
# Generate 5 ndarray of random numbers from a uniform distribution
np.random.rand(5)

array([0.28098375, 0.31868198, 0.70312611, 0.14142701, 0.25021061])

In [166]:
# My example code
# Generate 3 ndarray of random numbers from a uniform distribution
np.random.rand(3)

array([0.63233585, 0.34864953, 0.0640947 ])

In [167]:
# Example code from pdf
# Generate 5 ndarray of random numbers from the standard normal distribution
np.random.randn(5)

array([ 0.27798808,  0.0875398 , -0.62175167,  0.2394788 ,  0.26759665])

In [168]:
# My example code
# Generate 3 ndarray of random numbers from the standard normal distribution
np.random.randn(3)

array([ 1.18127908, -0.14459534,  0.63412103])

In [169]:
# Example code from pdf
# Generate a single or multiple random integers between [low, high)
np.random.randint(1,100)

53

In [170]:
# My example code
# Generate a single or multiple random integers between [low, high)
np.random.randint(1000,10000)

4197

In [171]:
# Example code from pdf
# with sizes
np.random.randint(1, 100, 15)

array([41, 98, 97,  1, 14, 79, 62,  9, 31, 50, 15, 36, 97, 42, 95])

In [172]:
# My example code
# with sizes
np.random.randint(1000, 10000, 5)

array([3260, 5540, 3692, 4822, 5017])

In [173]:
# Example code from pdf
A = np.random.randint(0, 100, 20).reshape(4, 5)
A

array([[20, 53, 82, 95, 84],
       [ 3, 80, 76, 87, 74],
       [24, 22, 66, 35, 81],
       [88,  5, 31, 46,  9]])

In [174]:
# My example code
U = np.random.randint(0, 100, 6).reshape(2, 3)
U

array([[29, 83, 88],
       [17, 64, 10]])

In [175]:
# Example code from pdf
# find samllest and largest value from matrix
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin()}')
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()}')

The smallest value in A is 3, and is a located at position 5
The largest value in A is 95, and is a located at position 3


In [176]:
# My example code
# find samllest and largest value from matrix
print(f'The smallest value in matrix U is {U.min()}, and it is located at position {U.argmin()}')
print(f'The largest value in matrix U is {U.max()}, and it is located at position {U.argmax()}')

The smallest value in matrix U is 10, and it is located at position 5
The largest value in matrix U is 88, and it is located at position 2


In [177]:
# Example code from pdf
# know what dimensions
A.shape

(4, 5)

In [178]:
# My example code
# know what dimensions
U.shape

(2, 3)

In [179]:
# Example code from pdf
# Another way
np.shape(A)

(4, 5)

In [180]:
# My example code
# Another way
np.shape(U)

(2, 3)

# Common Operations

In [181]:
# Example code from pdf
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


In [182]:
# My example code
U = np.arange(1, 8)
V = np.arange(1, 15, 2)
W = np.arange(0, 9).reshape(3, 3)
X = np.arange(0, 9).reshape(3, 3)
Y = np.arange(1, 16).reshape(3, 5)
Z = np.arange(15)
print(f'U: {U}')
print(f'V: {V}')
print('W:')
print(W)
print('X:')
print(X)
print('Y:')
print(Y)
print(f'Z: {Z}')

U: [1 2 3 4 5 6 7]
V: [ 1  3  5  7  9 11 13]
W:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
X:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Y:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Z: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [183]:
# Example code from pdf
# Add 2 arrays
A + B

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [184]:
# My example code
# Add 2 arrays
U + V

array([ 2,  5,  8, 11, 14, 17, 20])

In [185]:
# Example code from pdf
# Add 5 to every position
A + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [186]:
# My example code
# Add 5 to every position
U + 5

array([ 6,  7,  8,  9, 10, 11, 12])

In [187]:
# Example code from pdf
# Subtract array B from A
A - B

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14])

In [188]:
# My example code
# Subtract array V from U
U - V

array([ 0, -1, -2, -3, -4, -5, -6])

In [189]:
# Example code from pdf
# Subtract 5 from array A
A - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [190]:
# My example code
# Subtract 5 from array U
U - 5

array([-4, -3, -2, -1,  0,  1,  2])

In [191]:
# Example code from pdf
# Multiply both arrays
A * B

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190, 231, 276, 325,
       378, 435])

In [192]:
# My example code
# Multiply both arrays
U * V

array([ 1,  6, 15, 28, 45, 66, 91])

In [193]:
# Example code from pdf
# Multiply array A by 5
A * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [194]:
# My example code
# Multiply array u by 5
U * 5

array([ 5, 10, 15, 20, 25, 30, 35])

In [195]:
# Example code from pdf
# Divide both arrays
A / B

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154, 0.53333333, 0.52941176, 0.52631579,
       0.52380952, 0.52173913, 0.52      , 0.51851852, 0.51724138])

In [196]:
# My example code
# Divide both arrays
U / V

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154])

In [197]:
# Example code from pdf
# Divide array A by 2
A / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5])

In [198]:
# My example code
# Divide array U by 2
U / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [199]:
# Example code from pdf
np.matmul(C, D)

array([[ 2,  3],
       [ 6, 11]])

In [200]:
# My example code
np.matmul(W, X)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [201]:
# Example code from pdf
# Square root the matrix
np.sqrt(E)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [202]:
# My example code
# Square root the matrix
np.sqrt(Y)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [203]:
# Example code from pdf
# Log
np.log(E)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [204]:
# My example code
# Log
np.log(Y)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [205]:
# Example code from pdf
np.where(F%2==0, -1, F*100)

array([ -1, 100,  -1, 300,  -1, 500,  -1, 700,  -1, 900,  -1])

In [206]:
# My example code
np.where(Z % 2 == 0, -1, Z * 10)

array([ -1,  10,  -1,  30,  -1,  50,  -1,  70,  -1,  90,  -1, 110,  -1,
       130,  -1])

# Indexing

In [207]:
# Example code from pdf
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [208]:
# My example code
U = np.arange(25)
U

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [209]:
# Example code from pdf
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[14]: {A[14]}')

A[0]: 0
A[5]: 5
A[14]: 14


In [210]:
# My example code
print(f'U[2]: {U[2]}')
print(f'U[10]: {U[10]}')
print(f'U[24]: {U[24]}')

U[2]: 2
U[10]: 10
U[24]: 24


In [211]:
# Example code from pdf
# [start_index:stop_index]
A[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
# My example code
# [start_index:stop_index]
U[5:25]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [213]:
# Example code from pdf
# modify values
A[0:10] = 500
A

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  10,  11,  12,
        13,  14])

In [214]:
# My example code
# modify values
U[5:15] = 777
U

array([  0,   1,   2,   3,   4, 777, 777, 777, 777, 777, 777, 777, 777,
       777, 777,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [215]:
# Example code from pdf
# 2d array
B = np.arange(50).reshape(5, 10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [216]:
# My example code
# 2d array
V = np.arange(25).reshape(5, 5)
V

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [217]:
# Example code from pdf
# indexing 2d array
print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')

0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42


In [218]:
# My example code
# indexing 2d array
print(f'0th row and 3rd col in V: {V[0, 3]}')
print(f'2nd row and 1st col in V: {V[1, 0]}')
print(f'4th row and 4th col in V: {V[4, 4]}')

0th row and 3rd col in V: 3
2nd row and 1st col in V: 5
4th row and 4th col in V: 24


In [219]:
# Example code from pdf
# Selection parts of row and col from 2d array
B[0:2, 3:5]

array([[ 3,  4],
       [13, 14]])

In [220]:
# My example code 
# Selection parts of row and col from 2d array
V[0:3, 3:5]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

In [221]:
# Example code from pdf
# we can modify values like this
B[0:2, 3:5] = -1
B

array([[ 0,  1,  2, -1, -1,  5,  6,  7,  8,  9],
       [10, 11, 12, -1, -1, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [222]:
# My example code
# we can modify values like this
V[0:3, 3:5] = -2
V

array([[ 0,  1,  2, -2, -2],
       [ 5,  6,  7, -2, -2],
       [10, 11, 12, -2, -2],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [223]:
# Example code from pdf
C = np.arange(50).reshape(10, 5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [224]:
# My example code
W = np.arange(25).reshape(5, 5)
W

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [225]:
# Example code from pdf
# Using comparsion operators
C%2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [226]:
# My example code
# Using comparsion operators
W % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [227]:
# Example code from pdf
# call the sum function
(C%2 == 0).sum()

25

In [228]:
# My example code
# call the sum function
(W % 2 == 0).sum()

13

In [229]:
# Example code from pdf
# filter out false elements and keep true elements
C[C%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [230]:
# My example code
# filter out false elements and keep true elements
W[W % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])